[my_program]
# The command to use to launch the program
command="/usr/local/bin/nginx -c /etc/nginx/test.conf"
# The number of processes to start and keep running
numprocs=1
# Whether to start this program at launch or not
autostart=true
# Whether the program should be restarted "always", "never", or on "unexpected" exits
restart_when=unexpected
# Which exit codes represent an expected exit status
exit_codes="0,2"
# How long the program should be running after it’s started for it to be considered successfully started
start_time=5
# How long to wait after a graceful stop before killing the program
stop_time=10
# How many times a restart should be attempted before aborting
max_restarts=3
# Which signal should be used to stop (i.e. exit gracefully) the program
stop_signal=TERM
# Options to "discard" the program’s stdout/stderr or to redirect them to files
stdout="/tmp/nginx.stdout"
stderr="/tmp/nginx.stderr"
# Environment variables to set before launching the program
env="STARTED_BY=taskmaster,ANSWER=42"
# A working directory to set before launching the program
workdir=/tmp
# An umask to set before launching the program
umask=022

[my_other_program]
command=
numprocs=
autostart=
restart_when=
exit_codes=
start_time=
stop_time=
max_restarts=
stop_signal=
stdout=
stderr=
env=
workdir=
umask=